// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACk3zaEaEdn_06ykgNprRNqoZCdWo5KC8',
    appId: '1:549231030313:web:48ccc8ff8e456d407dec38',
    messagingSenderId: '549231030313',
    projectId: 'migrainedairy',
    authDomain: 'migrainedairy.firebaseapp.com',
    storageBucket: 'migrainedairy.firebasestorage.app',
    measurementId: 'G-FPM0CJZ8K4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwIOkbxFoIRZIBndTn6HQArMjLnz56Dyw',
    appId: '1:549231030313:android:e2eb7c273e7963e27dec38',
    messagingSenderId: '549231030313',
    projectId: 'migrainedairy',
    storageBucket: 'migrainedairy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr3BVmz1EYIThNR6kDLHpZ7FFhdM33amY',
    appId: '1:549231030313:ios:6d9323c413ee1cbc7dec38',
    messagingSenderId: '549231030313',
    projectId: 'migrainedairy',
    storageBucket: 'migrainedairy.firebasestorage.app',
    iosBundleId: 'com.example.migraineApp',
  );
}
